export const metadata = {
  title: 'Turbo Web',
  description: 'Generated by turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
